version: '3.8'

services:
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_NAME=${DB_NAME}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "tigres"]
      interval: 5s
      timeout: 3s
      retries: 5
    ports: 
      - 5432:5432
    volumes:
      - postgres-db:/var/lib/postgresql/data
    networks:
      - app-network

  bot:
    build:
      context: ./bot
    container_name: bot
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./bot/.env
    ports:
      - 8080:8080 
    volumes:
      - ./bot:/usr/src/app
    command: ["./main"]
    networks:
      - app-network

  api:
    build:
      context: ./api
    container_name: api
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./api/.env
    ports:
      - 3000:3000
    volumes:
      - ./api:/usr/src/app
    command: ["./main"]
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-db:
